org.gradle.jvmargs=-Xms512m -Xmx3072m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8
android.useAndroidX=true
org.gradle.daemon=false
# This newDsl flag was added by the Flutter template
# Opt out of AGP new DSL to maintain plugin compatibility
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
# Temporarily disable built-in Kotlin to allow older plugins to apply KGP
android.builtInKotlin=false
# Reduce concurrency on low-memory machines
org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.workers.max=1
android.enableJetifier=false
